name: asxab_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0

  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/fonts/gilroy/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-BoldItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
        - asset: assets/fonts/gilroy/Gilroy-HeavyItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
        - asset: assets/fonts/gilroy/Gilroy-LightItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/gilroy/Gilroy-MediumItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
        - asset: assets/fonts/gilroy/Gilroy-ThinItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
        - asset: assets/fonts/gilroy/Gilroy-UltraLightItalic.ttf
          style: italic